blank_issues_enabled: false
contact_links:
  - name: ‚ùì Questions
    url: https://github.com/enlightn/enlightn/discussions
    about: The issuer tracker is focused on reporting bugs or problems. Please use the Discussions tabs for questions!
  - name: üìö Documentation improvements
    url: https://github.com/enlightn/enlightn-docs
    about: Our documentation is open-source, you can make a PR with your suggested changes over there.
  - name: Commercial Support
    about: We offer email support on bug reports for Enlightn Pro customers and also offer consulting on boosting performance and security for your application. Email us at support@laravel-enlightn.com.
